-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceNamespaceManager/db/bs_namespacemanager_namespaces.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_namespacemanager_namespaces (
  ns_id INTEGER NOT NULL,
  ns_name BLOB NOT NULL,
  ns_is_talk SMALLINT NOT NULL,
  ns_is_content SMALLINT NOT NULL,
  PRIMARY KEY(ns_id)
);
